### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LightiDeveloperYT** [chr1s0x1/Elysian#1]
Unknown type name 'CodeDirectory'
Unknown type name 'CodeDirectory'
Use of undeclared identifier 'CS_CDHASH_LEN'

**Comment by chr1s0x1** [comment]
uh, idk how you got these errors, Elysian has defined these already. You must have tampered with the declares or the headers.

**Comment by K1ddH4z3** [comment]
> uh, idk how you got these errors, Elysian has defined these already. You must have tampered with the declares or the headers.


I literally tampered with nothing

**Comment by chr1s0x1** [comment]
check if the cs_blob.h header is in the include folder, then make sure it's added in the amfiutils.m file & amfidestroyer.m file as - #import "include/cs_blob.h"

**Comment by chr1s0x1** [comment]
the latest commit should fix this issue

**Comment by K1ddH4z3** [comment]
Now it works
Thanks.
