### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by K1ddH4z3** [chr1s0x1/Elysian#5]
/Users/Light/Desktop/Elysian/Elysian/amfidestroyer.m:178:77: Expected ';' at end of declaration

**Comment by chr1s0x1** [comment]
fixed in the most recent commit

**Comment by K1ddH4z3** [comment]
Showing Recent Messages
2 duplicate symbols for architecture arm64

**Comment by chr1s0x1** [comment]
I'll look into it when I can, although it's probably a simple fix that you can do yourself. What symbol is it saying is duplicate?

**Comment by K1ddH4z3** [comment]
duplicate symbol '_MISVSACI_actual_offset' in:
    /Users/Light/Library/Developer/Xcode/DerivedData/Elysian-ctyfjvugvjiyenfvtzqqemxovdux/Build/Intermediates.noindex/Elysian.build/Debug-iphoneos/Elysian.build/Objects-normal/arm64/amfidestroyer.o
    /Users/Light/Library/Developer/Xcode/DerivedData/Elysian-ctyfjvugvjiyenfvtzqqemxovdux/Build/Intermediates.noindex/Elysian.build/Debug-iphoneos/Elysian.build/Objects-normal/arm64/amfiutils.o

**Comment by chr1s0x1** [comment]
I can fix this when I have time, it should be an easy fix in the meantime for you

**Comment by chr1s0x1** [comment]
should be fixed in recent commits
